version: '3'
services:

  current-without-napi:
    build: ./current-without-napi
    environment:
      DATABASE_URL: postgresql://test:test@postgres:5432/test?schema=public

  current-with-napi:
    build: ./current-with-napi
    environment:
      DATABASE_URL: postgresql://test:test@postgres:5432/test?schema=public

  postgres:
    image: "postgres:11"
    ports:
      - "5432:5432"
    volumes:
      - "data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

volumes:
  data:
